In [1]:
import numpy as np

In [165]:
X = np.array([[1, 2, 3, 4], [-1, -2, -3, -4]])
W = np.array([[1, 2], [3, 4], [5, 5], [1, 6]])

In [166]:
X

array([[ 1,  2,  3,  4],
       [-1, -2, -3, -4]])

In [167]:
X @ W @ W.T

array([[ 124,  274,  375,  320],
       [-124, -274, -375, -320]])

In [168]:
X - X @ W @ W.T

array([[-123, -272, -372, -316],
       [ 123,  272,  372,  316]])

In [169]:
np.linalg.norm(X - X @ W @ W.T, 'f')**2

654706.0

In [170]:
(X - X @ W @ W.T).flatten()**2

array([ 15129,  73984, 138384,  99856,  15129,  73984, 138384,  99856])

In [160]:
def loss_Zach(W):
    error = []
    for row in X:
        error.append(np.linalg.norm(row - row @ W @ W.T)**2) #L2-norm
        
    return error, np.sum(error)

In [185]:
loss_Zach(W)

([327352.99999999994, 327352.99999999994], 654705.9999999999)

In [186]:
def loss_textbook(W):
    error = []
    for col in W.T:
        for row in X:
            print(row @ col * col.T)
            error.append(np.linalg.norm(row - row @ col * col.T)**2)
        
    return error, np.sum(error)

def loss_textbook_1(w):
    error = []
    
    y_sum_sq = []
    for row in X:
        y_sum_sq.append(np.linalg.norm(row)**2)
        
    for row in X:
        error.append(np.linalg.norm(row @ w)**2)
    
        
    return error, np.sum(y_sum_sq) - np.sum(error)

In [182]:
loss_textbook(W[:, 0])

ValueError: matmul: Input operand 1 does not have enough dimensions (has 0, gufunc core with signature (n?,k),(k,m?)->(n?,m?) requires 1)

In [187]:
loss_textbook_1(W[:, 0])

([676.0, 676.0], -1292.0)

In [124]:
W[:, 0]

array([1, 3, 5, 1])

In [126]:
Y[0] @ W[:, 0]

26

In [128]:
np.dot(Y[0], W[:, 0])

26

In [130]:
Y[0]

array([1, 2, 3, 4])